---

services:
  adminer:
    enabled: false
    version: latest
    ram: 256M
    service_name: Adminer
    service_url: http://{}
  mongo:
    enabled: false
    version: latest
    ram: 1024M
  mysql:
    enabled: false
    version: latest
    ram: 1024M
    root_password: root
  phpmyadmin:
    enabled: false
    version: latest
    ram: 256M
    upload_max_filesize: 256M
    service_name: phpMyAdmin
    service_url: http://{}
  postgres:
    enabled: false
    version: latest
    ram: 1024M
    password: postgres
  redis:
    enabled: false
    version: latest
    ram: 1024M
  sqlserver:
    enabled: false
    version: latest
    ram: 1024M
    password: sqlServer!Stakkr
    name: SQL Server
