---

services:
  adminer:
    enabled: false
    ram: 256M
    service_name: Adminer
    service_url: http://{} (works also in https)
    version: latest
  memcached:
    enabled: false
    ram: 1024M
    version: alpine
  mongo:
    enabled: false
    ram: 1024M
    version: latest
  mysql:
    enabled: false
    ram: 1024M
    root_password: root
    version: 5
  phpmyadmin:
    enabled: false
    ram: 256M
    service_name: phpMyAdmin
    service_url: http://{} (works also in https)
    upload_max_filesize: 256M
    version: latest
  postgres:
    enabled: false
    password: postgres
    ram: 1024M
    version: latest
  redis:
    enabled: false
    ram: 1024M
    version: latest
  sqlserver:
    enabled: false
    name: SQL Server
    password: sqlServer!Stakkr
    ram: 1024M
    version: latest
