version: "3.8"

services:
  adminer:
    container_name: ${COMPOSE_PROJECT_NAME}_adminer
    hostname: ${COMPOSE_PROJECT_NAME}_adminer
    image: edyan/adminer:${DOCKER_ADMINER_VERSION:-latest}
    labels:
      traefik.enable: "true"
      traefik.http.services.adminer.loadbalancer.server.port: 80
      traefik.http.routers.adminer.tls: "true"
      traefik.http.routers.adminer.rule: "Host(`adminer.${COMPOSE_PROJECT_NAME}.${PROXY_DOMAIN}`)"
    mem_limit: ${DOCKER_ADMINER_RAM:-256M}
    networks: [stakkr]
