version: '2.2'

services:
    adminer:
        image: edyan/adminer:${DOCKER_ADMINER_VERSION}
        mem_limit: ${DOCKER_ADMINER_RAM}
        container_name: ${COMPOSE_PROJECT_NAME}_adminer
        hostname: ${COMPOSE_PROJECT_NAME}_adminer
        networks: [stakkr]
        labels:
            - traefik.frontend.rule=Host:adminer.${COMPOSE_PROJECT_NAME}.${PROXY_DOMAIN}
