version: '2.2'

services:
    adminer:
        container_name: ${COMPOSE_PROJECT_NAME}_adminer
        hostname: ${COMPOSE_PROJECT_NAME}_adminer
        image: edyan/adminer:${DOCKER_ADMINER_VERSION:-latest}
        labels:
            - traefik.frontend.rule=Host:adminer.${COMPOSE_PROJECT_NAME}.${PROXY_DOMAIN:-localhost}
        mem_limit: ${DOCKER_ADMINER_RAM:-256M}
        networks: [stakkr]
