version: '2.2'

services:
    mongo:
        container_name: ${COMPOSE_PROJECT_NAME}_mongo
        image: mongo:${DOCKER_MONGO_VERSION:-latest}
        hostname: ${COMPOSE_PROJECT_NAME}_mongo
        labels:
            - traefik.enable=False
        mem_limit: ${DOCKER_MONGO_RAM:-1024M}
        networks: [stakkr]
        volumes:
            - ${COMPOSE_BASE_DIR}/data/mongo:/data/db:delegated
