version: '2.2'

services:
    mysql:
        image: mysql:${DOCKER_MYSQL_VERSION}
        mem_limit: ${DOCKER_MYSQL_RAM}
        container_name: ${COMPOSE_PROJECT_NAME}_mysql
        hostname: ${COMPOSE_PROJECT_NAME}_mysql
        networks: [stakkr]
        environment:
            MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_PASSWORD}
        volumes:
            - ${COMPOSE_BASE_DIR}/data/mysql:/var/lib/mysql
            - ${COMPOSE_BASE_DIR}/conf/mysql-override:/etc/mysql/conf.d
        labels:
            - traefik.enable=False
