version: '2.2'

services:
    mysql:
        container_name: ${COMPOSE_PROJECT_NAME}_mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD:-root}
        hostname: ${COMPOSE_PROJECT_NAME}_mysql
        image: mysql:${DOCKER_MYSQL_VERSION:-5}
        labels:
            - traefik.enable=False
        mem_limit: ${DOCKER_MYSQL_RAM:-1024M}
        networks: [stakkr]
        volumes:
            - ${COMPOSE_BASE_DIR}/conf/mysql-override:/etc/mysql/conf.d
            - ${COMPOSE_BASE_DIR}/data/mysql:/var/lib/mysql
