version: '2.2'

services:
    phpmyadmin:
        container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
        environment:
            PMA_USER: root
            PMA_HOST: mysql
            PMA_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD:-root}
            PHP_UPLOAD_MAX_FILESIZE: ${DOCKER_PHPMYADMIN_UPLOAD_MAX_FILESIZE:-256M}
            #PMA_ARBITRARY: 1
        hostname: ${COMPOSE_PROJECT_NAME}_phpmyadmin
        image: phpmyadmin/phpmyadmin:${DOCKER_PHPMYADMIN_VERSION:-latest}
        labels:
            - traefik.frontend.rule=Host:phpmyadmin.${COMPOSE_PROJECT_NAME}.${PROXY_DOMAIN}
        mem_limit: ${DOCKER_PHPMYADMIN_RAM:-256M}
        networks: [stakkr]
