version: '2.2'

services:
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:${DOCKER_PHPMYADMIN_VERSION}
        mem_limit: ${DOCKER_PHPMYADMIN_RAM}
        environment:
            PMA_USER: root
            PMA_HOSTS: mysql
            PMA_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD}
            PHP_UPLOAD_MAX_FILESIZE: ${DOCKER_PHPMYADMIN_UPLOAD_MAX_FILESIZE}
            #PMA_ARBITRARY: 1
        container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
        hostname: ${COMPOSE_PROJECT_NAME}_phpmyadmin
        networks: [stakkr]
        labels:
            - traefik.frontend.rule=Host:phpmyadmin.${COMPOSE_PROJECT_NAME}.${PROXY_DOMAIN}
