version: "3.8"

services:
  redis:
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    hostname: ${COMPOSE_PROJECT_NAME}_redis
    image: redis:${DOCKER_REDIS_VERSION:-latest}
    mem_limit: ${DOCKER_REDIS_RAM:-1024M}
    networks: [stakkr]
    volumes:
      - ${COMPOSE_BASE_DIR}/data/redis:/var/lib/redis
